name: base
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anaconda-anon-usage=0.5.0=py312hfc0e8ea_100
  - annotated-types=0.6.0=py312h06a4308_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - boltons=24.1.0=py312h06a4308_0
  - brotli-python=1.0.9=py312h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.2.25=h06a4308_0
  - certifi=2025.7.14=py312h06a4308_0
  - cffi=1.17.1=py312h1fdaa30_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - conda=25.1.1=py312h06a4308_0
  - conda-anaconda-telemetry=0.1.2=py312h06a4308_0
  - conda-anaconda-tos=0.1.2=py312h06a4308_0
  - conda-content-trust=0.2.0=py312h06a4308_1
  - conda-libmamba-solver=25.1.1=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py312h06a4308_0
  - conda-package-streaming=0.11.0=py312h06a4308_0
  - cpp-expected=1.1.0=hdb19cb5_0
  - cryptography=43.0.3=py312h7825ff9_1
  - distro=1.9.0=py312h06a4308_0
  - expat=2.6.4=h6a678d5_0
  - fmt=11.1.4=h07f6e7f_1
  - frozendict=2.4.2=py312h06a4308_0
  - icu=75.1=he02047a_0
  - idna=3.7=py312h06a4308_0
  - jsonpatch=1.33=py312h06a4308_1
  - jsonpointer=2.1=pyhd3eb1b0_0
  - krb5=1.21.3=h8a1dbc1_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - libarchive=3.8.1=gpl_h98cc613_100
  - libcurl=8.14.1=h332b0f4_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libexpat=2.6.4=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.1.0=h767d61c_3
  - libgcc-ng=15.1.0=h69a702a_3
  - libgomp=15.1.0=h767d61c_3
  - libiconv=1.18=h4ce23a2_1
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libmamba=2.3.0=h44402ff_1
  - libmambapy=2.3.0=py312hd15d01f_1
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libsolv=0.7.34=h9463b59_0
  - libsqlite=3.50.3=hee844dc_1
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_3
  - libstdcxx-ng=15.1.0=h4852527_3
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.8=h4bc477f_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lz4-c=1.10.0=h5888daf_1
  - lzo=2.10=h7b6447c_2
  - mamba=2.3.0=h233bd08_1
  - markdown-it-py=2.2.0=py312h06a4308_1
  - mdurl=0.1.0=py312h06a4308_0
  - menuinst=2.2.0=py312h06a4308_1
  - ncurses=6.4=h6a678d5_0
  - nlohmann_json=3.11.3=he02047a_1
  - openssl=3.5.1=h7b32b05_0
  - packaging=24.2=py312h06a4308_0
  - pcre2=10.45=hc749103_0
  - pip=25.0=py312h06a4308_0
  - platformdirs=3.10.0=py312h06a4308_0
  - pluggy=1.5.0=py312h06a4308_0
  - pybind11-abi=4=hd3eb1b0_1
  - pycosat=0.6.6=py312h5eee18b_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.10.3=py312h06a4308_0
  - pydantic-core=2.27.1=py312h4aa5aa6_0
  - pygments=2.15.1=py312h06a4308_1
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.2=hab00c5b_0_cpython
  - python_abi=3.12=8_cp312
  - readline=8.2=h5eee18b_0
  - reproc=14.2.4=h6a678d5_2
  - reproc-cpp=14.2.4=h6a678d5_2
  - requests=2.32.3=py312h06a4308_1
  - rich=13.9.4=py312h06a4308_0
  - ruamel.yaml=0.18.6=py312h5eee18b_0
  - ruamel.yaml.clib=0.2.8=py312h5eee18b_0
  - setuptools=75.8.0=py312h06a4308_0
  - simdjson=3.13.0=h84d6215_0
  - spdlog=1.8.1=h7739ffd_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.13=noxft_hd72426e_102
  - tqdm=4.67.1=py312he106c6f_0
  - truststore=0.10.0=py312h06a4308_0
  - typing-extensions=4.12.2=py312h06a4308_0
  - typing_extensions=4.12.2=py312h06a4308_0
  - urllib3=2.3.0=py312h06a4308_0
  - wheel=0.45.1=py312h06a4308_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - yaml-cpp=0.8.0=h6a678d5_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.19.0=py312h5eee18b_0
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.2.2
      - altair==5.5.0
      - array-record==0.7.1
      - astunparse==1.6.3
      - attrs==25.3.0
      - chex==0.1.89
      - cloudpickle==3.1.1
      - clu==0.0.12
      - connectomics==0.0.3
      - contourpy==1.3.1
      - cycler==0.12.1
      - dataclasses-json==0.6.7
      - decorator==5.2.1
      - distrax==0.1.5
      - dm-pix==0.4.4
      - dm-tree==0.1.9
      - edt==3.0.0
      - einops==0.8.1
      - etils==1.12.2
      - flatbuffers==25.2.10
      - flax==0.10.5
      - fonttools==4.57.0
      - fsspec==2025.3.2
      - gast==0.6.0
      - gin-config==0.5.0
      - google-pasta==0.2.0
      - grain-nightly==0.0.10
      - grpcio==1.71.0
      - h5py==3.13.0
      - humanize==4.12.2
      - imageio==2.37.0
      - immutabledict==4.2.1
      - importlib-resources==6.5.2
      - jax==0.5.3
      - jaxlib==0.5.3
      - jaxtyping==0.3.1
      - jinja2==3.1.6
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - keras==3.9.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - libclang==18.1.1
      - llvmlite==0.44.0
      - markdown==3.7
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib==3.10.1
      - ml-collections==1.0.0
      - ml-dtypes==0.5.1
      - more-itertools==10.6.0
      - msgpack==1.1.0
      - mypy-extensions==1.0.0
      - namex==0.0.8
      - narwhals==1.34.1
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numba==0.61.2
      - numpy==2.1.3
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - optax==0.2.4
      - optree==0.15.0
      - orbax-checkpoint==0.11.12
      - pandas==2.2.3
      - pillow==11.1.0
      - protobuf==5.29.4
      - pynndescent==0.5.13
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.2
      - referencing==0.36.2
      - rpds-py==0.24.0
      - scikit-image==0.25.2
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - seaborn==0.13.2
      - simplejson==3.20.1
      - six==1.17.0
      - sofima==0.1
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.19.0
      - tensorflow-probability==0.25.0
      - tensorstore==0.1.73
      - termcolor==3.0.1
      - tf-keras==2.19.0
      - threadpoolctl==3.6.0
      - tifffile==2025.3.30
      - toolz==1.0.0
      - treescope==0.1.9
      - typing-inspect==0.9.0
      - tzdata==2025.2
      - umap-learn==0.5.9.post2
      - wadler-lindig==0.1.4
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - zapbench==0.1.0
      - zipp==3.21.0
prefix: /home/user/miniconda3
